management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /private
      exposure:
        include: info, health
  endpoint:
    health:
      path: /health
      enabled: true
      probes:
        enabled: true
    info:
      path: /info
      enabled: true