spring:
  application:
    name: capitole-service
  datasource:
    url: jdbc:h2:mem:capitoledb
    driverClassName: org.h2.Driver
    username: ${USERNAME_DB:admin}
    password: ${PASSWORD_DB:admin}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-capitole