server:
  servlet:
    context-path: /ws/api/pineapple-service/

spring:
  application:
    name: pineapple-service
  profiles:
    include: common-swagger, common-management
  mapper:
    DEFAULT_VIEW_INCLUSION: true
  jackson:
    default-property-inclusion: non_empty
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  datasource:
    url: jdbc:h2:mem:pineappledb
    driverClassName: org.h2.Driver
    username: ${USERNAME_DB:admin}
    password: ${PASSWORD_DB:admin}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-pineapple
      settings:
        trace: true
        web-allow-others: false