DROP TABLE IF EXISTS PRICE;
DROP TABLE IF EXISTS BRAND;

CREATE TABLE BRAND
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);


CREATE TABLE PRICE
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID   BIGINT     NOT NULL,
    START_DATE TIMESTAMP  NOT NULL,
    END_DATE   TIMESTAMP  NOT NULL,
    PRICE_LIST INT        NOT NULL,
    PRODUCT_ID BIGINT     NOT NULL,
    PRIORITY   INT        NOT NULL,
    PRICE      DECIMAL    NOT NULL,
    CURR       VARCHAR(3) NOT NULL
);

ALTER TABLE PRICE
    ADD FOREIGN KEY (BRAND_ID)
        REFERENCES BRAND (ID);
